### ISSUE TITLE
Typo: "Montagtag"

### ISSUE THREAD

**Issue by davidak** [YU000jp/logseq-plugin-flex-date-format#10]
I found a typo in the german translation of "monday".

It uses "Montagtag", but needs to be just "Montag".

![Screenshot from 2024-02-04 22 16 38](https://github.com/YU000jp/logseq-plugin-flex-date-format/assets/91113/c4d72fa2-1671-4a2f-9687-4cf82972e7da)

I did not find it in the code, so i don't see how to fix it myself.

**Comment by YU000jp** [comment]
It may be a bug in the browser's built-in translation function.  Force the string to be replaced. 
"Montagtag" → "Montag".
I plan to fix it and release a new version.

**Comment by YU000jp** [comment]
I release it.

**Comment by davidak** [comment]
It's fixed. Thank you!

**Comment by davidak** [comment]
Oh, no. For some reason it's now "Motag".

![Screenshot from 2024-02-12 13 36 47](https://github.com/YU000jp/logseq-plugin-flex-date-format/assets/91113/50c0a688-3589-4441-bb59-6f7a4fb44029)

**Comment by YU000jp** [comment]
> Oh, no. For some reason it's now "Motag".
> 
> ![Screenshot from 2024-02-12 13 36 47](https://github.com/YU000jp/logseq-plugin-flex-date-format/assets/91113/50c0a688-3589-4441-bb59-6f7a4fb44029)
> 

I don't understand why that would be the case.  However, it allows string replacement in the same way as before.  Since the plugin does not have that translation list, it is probably a bug in the Chromium browser built into Electron, the software required to turn Logseq into an app. I will release it in the next version.

TODO
[ ] - Replace "Motag"

**Comment by YU000jp** [comment]
@davidak 
I release it. Please update and check.

**Comment by davidak** [comment]
Now it works correctly. Thanks a lot!

![Screenshot from 2024-02-25 06 44 34](https://github.com/YU000jp/logseq-plugin-flex-date-format/assets/91113/5cdff8b6-a3e4-4f57-aac4-34e02d12b59b)
