### ISSUE TITLE
Add german (de) localization

### ISSUE THREAD

**Issue by davidak** [YU000jp/logseq-plugin-flex-date-format#8]
I expected, that the "localize" mode would use the language set in logseq settings, but it is set at the bottom of the settings to default (seems to be en).

I want the displayed format to be `EEEE, dd.MM.yyyy`, which i had before in logseq, but with the weekday names in german. That language seem currently not supported. I could add it, if you document how new localizations can be added (would help more contributions). Or better you use an established library that supports all common languages.

The common date format in german is:

`dd.MM.yyyy`

https://de.wikipedia.org/wiki/DIN_5008#Schreibweise_des_Datums
https://de.wikipedia.org/wiki/Datumsformat#DIN_5008

German weekdays are:

> Montag (monday)
> Dienstag
> Mittwoch
> Donnerstag
> Freitag
> Samstag
> Sonntag

See https://de.wikipedia.org/wiki/Wochentag

The short form is:

> Mo.
> Di.
> Mi.
> Do.
> Fr.
> Sa.
> So.

It would be great to set short version optionally. Currently it's used by default in journal title and links, but i want the full weekday name.

**Comment by YU000jp** [comment]
This is achieved using functions included in the browser's built-in Javascript. If default is specified, it is based on the computer's specified language.  Maybe it is possible to add it to the locales in advanced options. I will check the locale support for Germany and release a new version.

**Comment by davidak** [comment]
I have my system and browser set to english (en) to be able to search for error messages easier. In logseq desktop, i have set the language to german.

**Comment by YU000jp** [comment]
I released a new version. Please specify the locale for "de-DE" in the bottom item of the plugin settings.

**Comment by YU000jp** [comment]
- [ ] TODO long instead of short

**Comment by davidak** [comment]
The Localize mode does work now. Only in `EEEE, dd.MM.yyyy` format, the day is still in english. If i understand the settings correctly, with `booleanJournalLinkLocalizeDayOfWeek` enabled, it should also get translated.

**Comment by YU000jp** [comment]
It wasn't working as configured. I have released a new version that includes those fixes.

**Comment by davidak** [comment]
Now it's perfect. Thanks a lot for your efforts!
